# Generated by Django 4.2.1 on 2023-08-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount',
            new_name='discount_percent',
        ),
    ]
