# Generated by Django 4.2.1 on 2023-07-09 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_addition',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
